### ISSUE TITLE
There is so many, just leaving a comment so I don'

### ISSUE THREAD

**Issue by KUPOkinz** [LeonPupier/Mensible#5]
t download this one again. Horrible.

**Comment by LeonPupier** [comment]
Hello,
I don't understand your problem...
Could you explain me more so I can help you?
Thank you in advance for your answer

**Comment by LeonPupier** [comment]
I did this project in order to develop my skills and to provide people who want a way to download music and video. Of course, I am not the only one to provide this kind of software and I am well aware of it. But how does it prevent me from offering my creations publicly?
I don't understand your comment and I hope that you have tested my application to make such a categorical judgment...
I would really like to know if you have tested **_Mensible_** and if you have noticed any problems. It would be more interesting to have a discussion than to reduce my work to a simple "Horrible"...
Of course, I'm still listening to you to improve my software.

_I will close this issue in 2 days if you do not decide to discuss..._

**Comment by LeonPupier** [comment]
Oh, I just saw that...
I think it would be better for you to let people who want to create what they want. Although many people are developing the same kind of software...
Have a nice day and I'll close this issue because I'm sure I won't get an answer from you.
_Léon Pupier_

![image](https://user-images.githubusercontent.com/100092382/168422437-b8d4c90a-dfa6-422f-8abf-d4659d996981.png)
